export const SLOGANS = [
    "Laundry Legends Unite!",
    "Spin Cycle Squad",
    "Wash Wizards Collective",
    "Cleaning up in Style",
    "Detergent Dynamos Unleashed",
    "Fabric Friends Forever",
    "Stain Busters Alliance",
    "Fold Force Five",
    "Lint Lovers League",
    "Fresh & Fluffy Crew",
    "Laundry Liberation League",
    "Thread Therapy Tribe",
    "Wrinkle Warriors Coalition",
    "The Rinse Rebels",
    "Folded Perfection Society",
    "Bleach Babes Brigade",
    "The Clean Dream Team",
    "Steam Team Connection",
    "Softness Syndicate",
    "Pressing for Excellence",
    "Drip Dry Dynasty",
    "Crisp and Clean Collective",
    "Lint-Free Living League",
    "Soap Opera Society",
    "Spotless Squad Syndicate",
    "Wash & Wear Warriors",
    "Laundry Lounge Legends",
    "Folding Fanatics Fellowship",
    "Iron Impressarios Inc.",
    "Delicate Cycle Crew",
    "Scent Sensation Society",
    "Thread Tidiers Tribe",
    "Bleach Blossoms Brotherhood",
    "Lint Liberation Legion",
    "Wrinkle-Free Warriors",
    "Fluff and Fold Family",
    "Steamy Situation Squad",
    "Laundry Lovebirds League",
    "Press & Progress Posse",
    "Spin Sisters Society",
    "Clothesline Connoisseurs",
    "Laundry Lords & Ladies",
    "Cotton Companions Collective",
    "Freshness Fanfare Force",
    "Wash Whiz Wonders",
    "Fold Fiesta Fellowship",
    "Scent Symphony Squad",
    "Chic & Clean Coalition",
    "Stain Slayer Society",
    "Whirlpool Wonders Union",
]

export default SLOGANS;